#!/usr/bin/env python3
"""Embed the reference run's output files into the lab site.

The simulation lets students download the three output files. The site has to
work from a file:// URL and from GitHub Pages with no server, so the files are
embedded as strings rather than fetched.

Source of truth is `reference-run/*.md`. Edit those, then run this.

    OUT_DIR=/path/to/cropco-agent-lab python3 scratchpad/gen_sim_outputs.py

Also embeds the three agent definition files from `.claude/agents/`, so the
"read the agent files" step of the exercise works offline too.
"""

import json
import os
import pathlib
import sys

ROOT = pathlib.Path(os.environ.get("OUT_DIR", pathlib.Path(__file__).resolve().parent.parent))

OUTPUTS = [
    ("ranked-farms.md", "The answer — six farms scored and ranked, four exclusions listed beneath"),
    ("NEEDS-HUMAN-REVIEW.md", "The interesting one — why four farms were not scored at all"),
    ("outreach-drafts.md", "Five drafts, plus what a person must check before any of them are sent"),
]

AGENTS = ["farm-researcher", "fit-scorer", "outreach-writer"]


def read(path: pathlib.Path) -> str:
    if not path.exists():
        sys.exit(f"missing: {path}")
    return path.read_text(encoding="utf-8")


def main() -> None:
    outputs = []
    for name, blurb in OUTPUTS:
        body = read(ROOT / "reference-run" / name)
        outputs.append({
            "name": name,
            "blurb": blurb,
            "lines": body.count("\n") + 1,
            "body": body,
        })

    agents = []
    for name in AGENTS:
        body = read(ROOT / ".claude" / "agents" / f"{name}.md")
        agents.append({"name": name, "body": body})

    payload = {"outputs": outputs, "agentFiles": agents}

    dest = ROOT / "docs" / "assets" / "sim-outputs.js"
    dest.write_text(
        "/* GENERATED by scratchpad/gen_sim_outputs.py — do not edit by hand.\n"
        " * Source of truth: reference-run/*.md and .claude/agents/*.md\n"
        " */\n"
        "window.SIM_OUTPUTS = " + json.dumps(payload, indent=2, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    total = sum(len(o["body"]) for o in payload["outputs"])
    print(f"wrote {dest.relative_to(ROOT)}  ({len(outputs)} outputs, {len(agents)} agent files, {total:,} chars)")


if __name__ == "__main__":
    main()
